#!/bin/bash

#
#  SPDX-FileCopyrightText 2023 Davide Garberi <dade.garberi@gmail.com>
#
#  SPDX-License-Identifier: LGPL-2.1-or-later
#

if [[ -f /opt/cppm/mode ]]; then
	mode=$(cat /opt/cppm/mode)
else
	mode="2"
fi

cores=$(nproc --ignore=1)

case "$mode" in
	"1")
		for ((policy = 0; policy <= $cores; policy++)); do
		echo "powersave" > "/sys/devices/system/cpu/cpufreq/policy$policy/scaling_governor"
		done
		;;

	"2")
		for ((policy = 0; policy <= $cores; policy++)); do
		echo "schedutil" > "/sys/devices/system/cpu/cpufreq/policy$policy/scaling_governor"
		done
		;;

	"3")
		for ((policy = 0; policy <= $cores; policy++)); do
		echo "performance" > "/sys/devices/system/cpu/cpufreq/policy$policy/scaling_governor"
		done
		;;
esac
