#!/bin/bash

if [[ -f /opt/powermodes/mode ]]; then
	mode=$(cat /opt/powermodes/mode)
else
	mode="2"
fi

cores=$(nproc)

case "$mode" in
	"1")
		for policy in {0..$cores}; do
		echo "powersave" > "/sys/devices/system/cpu/cpufreq/policy$policy/scaling_governor"
		done
		;;

	"2")
		for policy in {0..$cores}; do
		echo "schedutil" > "/sys/devices/system/cpu/cpufreq/policy$policy/scaling_governor"
		done
		;;

	"3")
		for policy in {0..$cores}; do
		echo "performance" > "/sys/devices/system/cpu/cpufreq/policy$policy/scaling_governor"
		done
		;;
esac
