#!/bin/bash

#
#  SPDX-FileCopyrightText 2023 Davide Garberi <dade.garberi@gmail.com>
#
#  SPDX-License-Identifier: LGPL-2.1-or-later
#

if [ ! -s /opt/cppm/mode ]; then
	echo "2" | install -D -m 666 /dev/stdin /opt/cppm/mode

	# After having written to ths mode file, systemd will trigger another run
	exit 1
fi

mode=$(cat /opt/cppm/mode)

case "$mode" in
	"1")
		echo "0" > "/sys/devices/system/cpu/cpu4/online"
		echo "0" > "/sys/devices/system/cpu/cpu5/online"
		cores=$(nproc --ignore=1)
		for ((i = 0; i <= $cores; i++)); do
		echo "powersave" > "/sys/devices/system/cpu/cpufreq/policy$i/scaling_governor"
		done
		;;

	"2")
		echo "1" > "/sys/devices/system/cpu/cpu4/online"
		echo "1" > "/sys/devices/system/cpu/cpu5/online"
		cores=$(nproc --ignore=1)
		for ((i = 0; i <= $cores; i++)); do
		echo "schedutil" > "/sys/devices/system/cpu/cpufreq/policy$i/scaling_governor"
		done
		;;

	"3")
		echo "1" > "/sys/devices/system/cpu/cpu4/online"
		echo "1" > "/sys/devices/system/cpu/cpu5/online"
		cores=$(nproc --ignore=1)
		for ((i = 0; i <= $cores; i++)); do
		echo "performance" > "/sys/devices/system/cpu/cpufreq/policy$i/scaling_governor"
		done
		;;
esac
